### ISSUE TITLE
Does'nt work

### ISSUE THREAD

**Issue by Frantzd** [victorfence/scrapbook-easy-viewer#1]
Hello,

when I load the read.html file from my scrapbook folder, I only get small boxes with
"null" or "origin" written on them.

Regards.

**Comment by victorfence** [comment]
Hello Frantzd,

Did you open read.html with firefox? Did you put the 3 files into right place?
Or can you provide more details such as OS platform, browser with version and so on?

Cheers

**Comment by Frantzd** [comment]
Hello,

Yes I did what you say. 
I tried on Ubuntu 16.04.4 LTS with Firefox 60.0b6 (64 bits) and on Ubuntu 14.04.5 LTS with Firefox 56.0 (61 bits).

Regards.

**Comment by victorfence** [comment]
Hi Frantzd,

I tried again in ubuntu12.04 with firefox14 and windows xp with firefox 56, and it works, sorry for I have no same env as yours, But it seems not caused by OS or browser.

I'm guessing:
1 Coding problem, please try my new read.html (new line \<meta charset="utf-8"/\> added)
2 Namespace problem of rdf file, please try my new pushed example scrapbook.rdf
   if this working, please compire the file with yours to see what's different.
3 If above not work, please try to find if there are error reports inside firefox console (control + shift + k)

Regards.

**Comment by Frantzd** [comment]
Hi,

1 : where is your new read.html file ?
2 : ok, it works.
3 : as seen on the output of the console, it seems to be effectively a problem of character coding
(sorry, it's in french) :

> L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert.

Regards.

**Comment by victorfence** [comment]
Sorry, I miss pushed that file.
You can fetch new read.html from my last commit now :)

**Comment by Frantzd** [comment]
Always the same problem with my scrapbook.

Console > JS :

> L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final. Consulter http://xhr.spec.whatwg.org/ pour plus d’informations.  read.js:146

Console > CSS  :

> Erreur d’analyse de la valeur pour « width ».  Déclaration abandonnée.  read.html:28:9
> Erreur d’analyse de la valeur pour « width ».  Déclaration abandonnée.  read.html:29:9

**Comment by victorfence** [comment]
Hi, please check if your scrapbook.rdf is in charset utf-8.

Also, please check top part of your scrapbook.rdf. Such as:
<RDF:RDF xmlns:NS1="http://amb.vis.ne.jp/mozilla/scrapbook-rdf#"
         xmlns:NC="http://home.netscape.com/NC-rdf#"
         xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
Is the same?

**Comment by victorfence** [comment]
It will helps if you provide more content about your scrapbook.rdf
For example, the title defined in my rdf is looks like:
 <RDF:Description RDF:about="urn:scrapbook:item20170705091001"
                   NS1:id="20170705091001"
                   NS1:type=""
                   **NS1:title="test item 1"**
                   NS1:chars=""
                   NS1:comment=""
                   NS1:source="http://google.com"
                   NS1:icon="" />
I wonder if there's  something difference.
Thanks

**Comment by Frantzd** [comment]
Yes it is in utf-8.

Here it is :
 
```
<?xml version="1.0"?>
<RDF:RDF xmlns:NS24="http://amb.vis.ne.jp/mozilla/scrapbook-rdf#"
         xmlns:NC="http://home.netscape.com/NC-rdf#"
         xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <RDF:Description RDF:about="urn:scrapbook:item20121126093741"
                   NS24:id="20121126093741"
                   NS24:type=""
                   NS24:title="Some text"
                   NS24:chars="UTF-8"
                   NS24:comment=""
                   NS24:source="http://www.toto.fr/version-francaise/l-ecole/organisation/financial-service-46332.kjsp?RH=1_9"
                   NS24:icon="resource://scrapbook/data/20121126093741/favicon.p
ng" />
(...)


```

**Comment by victorfence** [comment]
That is it ...
As a temporary solution please replace all NS1 to NS24 in read.js with text editor.
Save it and try again.

**Comment by Frantzd** [comment]
It works ! Thanks !

**Comment by victorfence** [comment]
Glad to hear that, I'll try to fix it in new version, thanks for bug reporting.

**Comment by victorfence** [comment]
Fixed, now close.
